<a href="https://colab.research.google.com/github/Debayan97531/MatpllotlibJupyter/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy tutorial**


In [ ]:
import numpy as np
import sklearn

In [ ]:
myarr=np.array([3,6,998988,9],np.int64)

In [ ]:
myarr

array([     3,      6, 998988,      9])

In [ ]:
myarr[1]

6

In [ ]:
myarr.shape

(4,)

In [ ]:
myarr.dtype

dtype('int64')

In [ ]:
myarr[3]=89

In [ ]:
myarr

array([     3,      6, 998988,     89])

**Array Creation from other python structures**


In [ ]:
listarr=np.array([[1,5,33],[6,7,8],[8,966,8]])

In [ ]:
listarr

array([[  1,   5,  33],
       [  6,   7,   8],
       [  8, 966,   8]])

In [ ]:
listarr.dtype

dtype('int64')

In [ ]:
listarr.shape

(3, 3)

In [ ]:
listarr.size

9

In [ ]:
np.array({34,67,55})

array({34, 67, 55}, dtype=object)

In [ ]:
zero=np.zeros((2,6))

In [ ]:
zero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
zero.shape

(2, 6)

In [ ]:
zero.dtype

dtype('float64')

In [ ]:
zero.size

12

In [ ]:
zero.all

<function ndarray.all>

In [ ]:
rng=np.arange(18)

In [ ]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
lspace=np.linspace(1,50,11)

In [ ]:
lspace

array([ 1. ,  5.9, 10.8, 15.7, 20.6, 25.5, 30.4, 35.3, 40.2, 45.1, 50. ])

In [ ]:
emp=np.empty((4,5))

In [ ]:
emp

array([[2.52846513e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [ ]:
emp_like=np.empty_like(lspace)

In [ ]:
emp_like

array([ 1. ,  5.9, 10.8, 15.7, 20.6, 25.5, 30.4, 35.3, 40.2, 45.1, 50. ])

In [ ]:
ide=np.identity(45)

In [ ]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
ide.shape

(45, 45)

In [ ]:
amm=np.arange(99)

In [ ]:
amm

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
amm.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
amm

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
amm=amm.reshape(9,11)

In [ ]:
amm

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [ ]:
amm=amm.ravel()

In [ ]:
amm.shape

(99,)

In [ ]:
x=np.array([[1,2,3],[4,5,6],[7,1,0]])

In [ ]:
ar=np.array(x)

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.sum(axis=0)

array([12,  8,  9])

In [ ]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
ar.flat

In [ ]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
ar.ndim

2

In [ ]:
ar.size

9

In [ ]:
ar.nbytes#total bytes consumed

72

In [ ]:
one=np.array([3,5,77,55,12])

In [ ]:
one.argmax()

2

In [ ]:
one.argmin()

0

In [ ]:
one.argsort()

array([0, 1, 4, 3, 2])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.argmin()

8

In [ ]:
ar.argmax()

6

In [ ]:
ar.argmax(axis=0)#7,5,6 -->chcking column wise

array([2, 1, 1])

In [ ]:
ar.argmax(axis=1) #3,6,7 -->checking row wise

array([2, 2, 0])

In [ ]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [ ]:
ar.argsort(axis=1)#compaaring 1,2,3 .. 4,5,6 ..7,1,0

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [ ]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [ ]:
ar.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar2=np.array([[1,4,5],[5,6,9],[6,33,1]])

In [ ]:
ar2

array([[ 1,  4,  5],
       [ 5,  6,  9],
       [ 6, 33,  1]])

In [ ]:
ar+ar2

array([[ 2,  6,  8],
       [ 9, 11, 15],
       [13, 34,  1]])

In [ ]:
[3,33]+[22,2]

[3, 33, 22, 2]

In [ ]:
ar*ar2

array([[ 1,  8, 15],
       [20, 30, 54],
       [42, 33,  0]])

In [ ]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [ ]:
ar.sum()

29

In [ ]:
ar.min()

0

In [ ]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [ ]:
type(np.where(ar>5))

tuple

In [ ]:
np.count_nonzero(ar)

8

In [ ]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [ ]:
import sys

In [ ]:
py_ar=[0,5,4,6,3]

In [ ]:
np_ar=[9,6,22]

In [ ]:
sys.getsizeof(1)*len(py_ar)

140

In [ ]:
np_ar=np.array(py_ar)

In [ ]:
np_ar.itemsize * np_ar.size

40

In [ ]:
np_ar.tolist()

[0, 5, 4, 6, 3]